version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-structure-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=America/New_York  # Set timezone for market hours
    volumes:
      - ./logs:/app/logs  # Optional: mount logs directory
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://httpbin.org/status/200', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  trading-network:
    driver: bridge

volumes:
  logs:
    driver: local 